<?php

declare(strict_types=1);

namespace CodebarAg\MFiles\DTO\User;

use Illuminate\Support\Arr;

/**
 * DTO for ServerVaultCapabilities from the /session response
 */
final class ServerVaultCapabilities
{
    public function __construct(
        public readonly ?bool $VaultLoginAccountsSupported,
        public readonly ?bool $PublicLinkSharingSupported,
        public readonly ?bool $LatestVersionPublicLinkSharingSupported,
        public readonly ?bool $FacetSearchSupported,
        public readonly ?bool $PropertyDefSearchabilitySupported,
        public readonly ?bool $AutomaticMetadataSupported,
        public readonly ?bool $FileStreamingSupported,
        public readonly ?bool $SearchOptionsSupported,
        public readonly ?bool $JSONExtApplicationsSupported,
        public readonly ?bool $SearchReferencedValueListItemsSupported,
        public readonly ?bool $GetTextContentWithOptionsSupported,
        public readonly ?bool $DetectTextLanguageSupported,
        public readonly ?bool $ObjectDataRetrievalInChunksSupported,
        public readonly ?bool $SettingsManagerSupported,
        public readonly ?bool $ExternalRepositoryObjectMigrationSupported,
        public readonly ?bool $ClientHttpApiSupported,
        public readonly ?bool $ReverseGroupingLevelSupported,
        public readonly ?bool $ReplicationConfigurationIDSupported,
        public readonly ?bool $AsyncNACLChangePropagationSupported,
        public readonly ?bool $AsyncTasksRetrievalSupported,
        public readonly ?bool $FindDuplicatesSupported,
        public readonly ?bool $FavorFullTextSearchSupported,
        public readonly ?bool $ApplicationTaskQueueSupported,
        public readonly ?bool $ObjectPermissionsForClientSupported,
        public readonly ?bool $UndeleteUserAccountByGUIDSupported,
        public readonly ?bool $UseUserVisibleACLInSearches,
        public readonly ?bool $NamedValueStorageConflictDetectionSupported,
        public readonly ?bool $HierarchicalObjectTypePropertiesSupported,
        public readonly ?bool $EmbeddingToSharePointSupported,
        public readonly ?bool $EmbeddingToSalesforceSupported,
        public readonly ?bool $AsyncModifyObjectClassSupported,
        public readonly ?bool $WebUserInterfaceSupported,
        public readonly ?bool $RemoveFromRecentsSupported,
        public readonly ?bool $EmbeddingToGoogleGSuiteSupported,
        public readonly ?bool $FullControlVaultUserCanModifyCodeSupported,
        public readonly ?bool $EmbeddingToArcGisSupported,
        public readonly ?bool $WebClientsProductionTelemetryEnabled,
        public readonly ?bool $SharedLinkBasedWOPIOperationSupported,
        public readonly ?bool $MdccResolvedOnServer,
        public readonly ?bool $GreenLightsSupported,
        public readonly ?bool $NewWebWOPICoAuthoringSupported,
        public readonly ?bool $MFilesLinkSupported,
        public readonly ?bool $MdccConversionOnServer,
        public readonly ?bool $VaultLevelOptimizationJobsSupported,
        public readonly ?bool $ImportViewsWithOlderLastModifiedSupported,
        public readonly ?bool $VisitorLinksSupported,
        public readonly ?bool $AddObjectWithMultipleFilesSupported,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            VaultLoginAccountsSupported: Arr::get($data, 'VaultLoginAccountsSupported'),
            PublicLinkSharingSupported: Arr::get($data, 'PublicLinkSharingSupported'),
            LatestVersionPublicLinkSharingSupported: Arr::get($data, 'LatestVersionPublicLinkSharingSupported'),
            FacetSearchSupported: Arr::get($data, 'FacetSearchSupported'),
            PropertyDefSearchabilitySupported: Arr::get($data, 'PropertyDefSearchabilitySupported'),
            AutomaticMetadataSupported: Arr::get($data, 'AutomaticMetadataSupported'),
            FileStreamingSupported: Arr::get($data, 'FileStreamingSupported'),
            SearchOptionsSupported: Arr::get($data, 'SearchOptionsSupported'),
            JSONExtApplicationsSupported: Arr::get($data, 'JSONExtApplicationsSupported'),
            SearchReferencedValueListItemsSupported: Arr::get($data, 'SearchReferencedValueListItemsSupported'),
            GetTextContentWithOptionsSupported: Arr::get($data, 'GetTextContentWithOptionsSupported'),
            DetectTextLanguageSupported: Arr::get($data, 'DetectTextLanguageSupported'),
            ObjectDataRetrievalInChunksSupported: Arr::get($data, 'ObjectDataRetrievalInChunksSupported'),
            SettingsManagerSupported: Arr::get($data, 'SettingsManagerSupported'),
            ExternalRepositoryObjectMigrationSupported: Arr::get($data, 'ExternalRepositoryObjectMigrationSupported'),
            ClientHttpApiSupported: Arr::get($data, 'ClientHttpApiSupported'),
            ReverseGroupingLevelSupported: Arr::get($data, 'ReverseGroupingLevelSupported'),
            ReplicationConfigurationIDSupported: Arr::get($data, 'ReplicationConfigurationIDSupported'),
            AsyncNACLChangePropagationSupported: Arr::get($data, 'AsyncNACLChangePropagationSupported'),
            AsyncTasksRetrievalSupported: Arr::get($data, 'AsyncTasksRetrievalSupported'),
            FindDuplicatesSupported: Arr::get($data, 'FindDuplicatesSupported'),
            FavorFullTextSearchSupported: Arr::get($data, 'FavorFullTextSearchSupported'),
            ApplicationTaskQueueSupported: Arr::get($data, 'ApplicationTaskQueueSupported'),
            ObjectPermissionsForClientSupported: Arr::get($data, 'ObjectPermissionsForClientSupported'),
            UndeleteUserAccountByGUIDSupported: Arr::get($data, 'UndeleteUserAccountByGUIDSupported'),
            UseUserVisibleACLInSearches: Arr::get($data, 'UseUserVisibleACLInSearches'),
            NamedValueStorageConflictDetectionSupported: Arr::get($data, 'NamedValueStorageConflictDetectionSupported'),
            HierarchicalObjectTypePropertiesSupported: Arr::get($data, 'HierarchicalObjectTypePropertiesSupported'),
            EmbeddingToSharePointSupported: Arr::get($data, 'EmbeddingToSharePointSupported'),
            EmbeddingToSalesforceSupported: Arr::get($data, 'EmbeddingToSalesforceSupported'),
            AsyncModifyObjectClassSupported: Arr::get($data, 'AsyncModifyObjectClassSupported'),
            WebUserInterfaceSupported: Arr::get($data, 'WebUserInterfaceSupported'),
            RemoveFromRecentsSupported: Arr::get($data, 'RemoveFromRecentsSupported'),
            EmbeddingToGoogleGSuiteSupported: Arr::get($data, 'EmbeddingToGoogleGSuiteSupported'),
            FullControlVaultUserCanModifyCodeSupported: Arr::get($data, 'FullControlVaultUserCanModifyCodeSupported'),
            EmbeddingToArcGisSupported: Arr::get($data, 'EmbeddingToArcGisSupported'),
            WebClientsProductionTelemetryEnabled: Arr::get($data, 'WebClientsProductionTelemetryEnabled'),
            SharedLinkBasedWOPIOperationSupported: Arr::get($data, 'SharedLinkBasedWOPIOperationSupported'),
            MdccResolvedOnServer: Arr::get($data, 'MdccResolvedOnServer'),
            GreenLightsSupported: Arr::get($data, 'GreenLightsSupported'),
            NewWebWOPICoAuthoringSupported: Arr::get($data, 'NewWebWOPICoAuthoringSupported'),
            MFilesLinkSupported: Arr::get($data, 'MFilesLinkSupported'),
            MdccConversionOnServer: Arr::get($data, 'MdccConversionOnServer'),
            VaultLevelOptimizationJobsSupported: Arr::get($data, 'VaultLevelOptimizationJobsSupported'),
            ImportViewsWithOlderLastModifiedSupported: Arr::get($data, 'ImportViewsWithOlderLastModifiedSupported'),
            VisitorLinksSupported: Arr::get($data, 'VisitorLinksSupported'),
            AddObjectWithMultipleFilesSupported: Arr::get($data, 'AddObjectWithMultipleFilesSupported'),
        );
    }

    public function toArray(): array
    {
        return [
            'vaultLoginAccountsSupported' => $this->VaultLoginAccountsSupported,
            'publicLinkSharingSupported' => $this->PublicLinkSharingSupported,
            'latestVersionPublicLinkSharingSupported' => $this->LatestVersionPublicLinkSharingSupported,
            'facetSearchSupported' => $this->FacetSearchSupported,
            'propertyDefSearchabilitySupported' => $this->PropertyDefSearchabilitySupported,
            'automaticMetadataSupported' => $this->AutomaticMetadataSupported,
            'fileStreamingSupported' => $this->FileStreamingSupported,
            'searchOptionsSupported' => $this->SearchOptionsSupported,
            'jsonExtApplicationsSupported' => $this->JSONExtApplicationsSupported,
            'searchReferencedValueListItemsSupported' => $this->SearchReferencedValueListItemsSupported,
            'getTextContentWithOptionsSupported' => $this->GetTextContentWithOptionsSupported,
            'detectTextLanguageSupported' => $this->DetectTextLanguageSupported,
            'objectDataRetrievalInChunksSupported' => $this->ObjectDataRetrievalInChunksSupported,
            'settingsManagerSupported' => $this->SettingsManagerSupported,
            'externalRepositoryObjectMigrationSupported' => $this->ExternalRepositoryObjectMigrationSupported,
            'clientHttpApiSupported' => $this->ClientHttpApiSupported,
            'reverseGroupingLevelSupported' => $this->ReverseGroupingLevelSupported,
            'replicationConfigurationIdSupported' => $this->ReplicationConfigurationIDSupported,
            'asyncNaclChangePropagationSupported' => $this->AsyncNACLChangePropagationSupported,
            'asyncTasksRetrievalSupported' => $this->AsyncTasksRetrievalSupported,
            'findDuplicatesSupported' => $this->FindDuplicatesSupported,
            'favorFullTextSearchSupported' => $this->FavorFullTextSearchSupported,
            'applicationTaskQueueSupported' => $this->ApplicationTaskQueueSupported,
            'objectPermissionsForClientSupported' => $this->ObjectPermissionsForClientSupported,
            'undeleteUserAccountByGuidSupported' => $this->UndeleteUserAccountByGUIDSupported,
            'useUserVisibleAclInSearches' => $this->UseUserVisibleACLInSearches,
            'namedValueStorageConflictDetectionSupported' => $this->NamedValueStorageConflictDetectionSupported,
            'hierarchicalObjectTypePropertiesSupported' => $this->HierarchicalObjectTypePropertiesSupported,
            'embeddingToSharePointSupported' => $this->EmbeddingToSharePointSupported,
            'embeddingToSalesforceSupported' => $this->EmbeddingToSalesforceSupported,
            'asyncModifyObjectClassSupported' => $this->AsyncModifyObjectClassSupported,
            'webUserInterfaceSupported' => $this->WebUserInterfaceSupported,
            'removeFromRecentsSupported' => $this->RemoveFromRecentsSupported,
            'embeddingToGoogleGSuiteSupported' => $this->EmbeddingToGoogleGSuiteSupported,
            'fullControlVaultUserCanModifyCodeSupported' => $this->FullControlVaultUserCanModifyCodeSupported,
            'embeddingToArcGisSupported' => $this->EmbeddingToArcGisSupported,
            'webClientsProductionTelemetryEnabled' => $this->WebClientsProductionTelemetryEnabled,
            'sharedLinkBasedWopiOperationSupported' => $this->SharedLinkBasedWOPIOperationSupported,
            'mdccResolvedOnServer' => $this->MdccResolvedOnServer,
            'greenLightsSupported' => $this->GreenLightsSupported,
            'newWebWopiCoAuthoringSupported' => $this->NewWebWOPICoAuthoringSupported,
            'mFilesLinkSupported' => $this->MFilesLinkSupported,
            'mdccConversionOnServer' => $this->MdccConversionOnServer,
            'vaultLevelOptimizationJobsSupported' => $this->VaultLevelOptimizationJobsSupported,
            'importViewsWithOlderLastModifiedSupported' => $this->ImportViewsWithOlderLastModifiedSupported,
            'visitorLinksSupported' => $this->VisitorLinksSupported,
            'addObjectWithMultipleFilesSupported' => $this->AddObjectWithMultipleFilesSupported,
        ];
    }
}
